apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal-system
commonLabels:
  app: temporal
  app.kubernetes.io/name: "temporal"
configMapGenerator:
  - name: temporal-config
    files:
      - config/base.yaml
      - config/postgres.yaml
  - name: temporal-dynamic-config
    files:
      - dynamicconfig/development.yaml
resources:
  - service.yaml
  - statefulset.yaml
