---
apiVersion: v1
kind: Service
metadata:
  name: temporal-service
  labels:
    app: temporal-service
spec:
  type: NodePort
  selector:
    app: temporal
  ports:
    - name: "temporal"
      port: 7233
      targetPort: 7233
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  clusterIP: None
  selector:
    app: temporal
  ports:
    - name: "frontend-grpc"
      port: 7233
      targetPort: 7233
    - name: "history-grpc"
      port: 7234
      targetPort: 7234
    - name: "matching-grpc"
      port: 7235
      targetPort: 7235
    - name: "worker-grpc"
      port: 7239
      targetPort: 7239
    - name: "frontend-mem"
      port: 6933
      targetPort: 6933
    - name: "history-mem"
      port: 6934
      targetPort: 6934
    - name: "matching-mem"
      port: 6935
      targetPort: 6935
    - name: "worker-mem"
      port: 6939
      targetPort: 6939
