---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - datalake.h7kanna.dev
  resources:
  - hudisparkqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datalake.h7kanna.dev
  resources:
  - hudisparkqueries/finalizers
  verbs:
  - update
- apiGroups:
  - datalake.h7kanna.dev
  resources:
  - hudisparkqueries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - datalake.h7kanna.dev
  resources:
  - huditables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datalake.h7kanna.dev
  resources:
  - huditables/finalizers
  verbs:
  - update
- apiGroups:
  - datalake.h7kanna.dev
  resources:
  - huditables/status
  verbs:
  - get
  - patch
  - update
