apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal-system
commonLabels:
  app: postgres
  app.kubernetes.io/name: "postgres"
configMapGenerator:
  - name: postgres-config
    envs:
      - config/postgres.env
  - name: schema-config
    envs:
      - config/schema.env
resources:
  - postgres.yaml
  - schema.yaml
generatorOptions:
  labels:
    type: postgres
  annotations:
    note: postgres
